locations: [
  {x: 0.0, y: 0.0},
  {x: 1.0, y: 1.0},
  {x: 2.0, y: 2.0},
  {x: 3.0, y: 3.0},
  {x: 4.0, y: 4.0},
  {x: 5.0, y: 5.0},
]
allowed_moves: [
    [1, 2],
    [2, 3],
    [3, 4],
    [4, 5],
    [5, 0],
    [0, 1]
]
